/**
 * Canonical Murmur house-agent catalog shared across services.
 *
 * This module is the single source of truth for the built-in Nova, Rex, and
 * Sage personas described in Section 3.3 of the technical specification. The
 * API seed flow and the agent orchestrator both consume these definitions so
 * voice, styling, and personality data stay perfectly aligned.
 */

import type { TtsProvider } from "./types.js";

/**
 * Stable identifier values for the built-in Murmur agents.
 *
 * These IDs are configuration keys, not database primary keys. Persisted agent
 * rows continue to use UUIDs generated by PostgreSQL.
 */
export const HOUSE_AGENT_IDS = ["nova", "rex", "sage"] as const;

/**
 * Literal union of the supported built-in Murmur agents.
 */
export type HouseAgentId = (typeof HOUSE_AGENT_IDS)[number];

/**
 * Hex color string used for room-stage styling and avatar accents.
 */
type HexColor = `#${string}`;

/**
 * Shape of a canonical built-in agent definition.
 */
export interface HouseAgentDefinition {
  id: HouseAgentId;
  name: string;
  personality: string;
  voiceId: string;
  ttsProvider: TtsProvider;
  accentColor: HexColor;
  avatarUrl: string;
}

/**
 * Section 3.3 house-agent definitions used for initial seed data and future
 * orchestration setup.
 */
export const HOUSE_AGENTS = [
  {
    id: "nova",
    name: "Nova",
    personality: `You are Nova, a curious and optimistic AI with a background in technology
and futurism. You love exploring "what if" scenarios and tend to see the positive
potential in new developments. You speak with enthusiasm but back up your points
with concrete examples. You occasionally use metaphors from science fiction.`,
    voiceId: "cartesia_voice_id_nova",
    ttsProvider: "cartesia",
    accentColor: "#00D4FF",
    avatarUrl: "/agents/nova.png",
  },
  {
    id: "rex",
    name: "Rex",
    personality: `You are Rex, a sharp-witted skeptic and devil's advocate. You have deep
expertise in philosophy and economics. You challenge assumptions and push back on
overly optimistic takes with rigorous logic. Your tone is confident, occasionally
sarcastic, but never mean-spirited. You respect strong arguments even when you
disagree.`,
    voiceId: "elevenlabs_voice_id_rex",
    ttsProvider: "elevenlabs",
    accentColor: "#FF6B35",
    avatarUrl: "/agents/rex.png",
  },
  {
    id: "sage",
    name: "Sage",
    personality: `You are Sage, a calm and thoughtful synthesizer. Your expertise spans
psychology, culture, and the humanities. You listen carefully to both sides and find
nuanced middle ground. You often reframe debates by introducing perspectives others
haven't considered. You speak slowly and deliberately, using relatable analogies.`,
    voiceId: "cartesia_voice_id_sage",
    ttsProvider: "cartesia",
    accentColor: "#A855F7",
    avatarUrl: "/agents/sage.png",
  },
] as const satisfies readonly HouseAgentDefinition[];

const HOUSE_AGENT_LOOKUP = new Map(
  HOUSE_AGENTS.map((agent) => [agent.id, agent]),
);

/**
 * Returns a built-in agent definition by its stable configuration ID.
 *
 * @param agentId - Stable configuration key such as `nova`.
 * @returns The matching house-agent definition.
 * @throws {Error} When the ID does not map to a canonical built-in agent.
 */
export function getHouseAgentById(agentId: HouseAgentId): HouseAgentDefinition {
  const match = HOUSE_AGENT_LOOKUP.get(agentId);

  if (!match) {
    throw new Error(
      `Unknown house agent "${agentId}". Update packages/shared/src/house-agents.ts and re-run the command.`,
    );
  }

  return match;
}
